### PR TITLE
updating node-version for build.yml

### PR DESCRIPTION
**Pull request by Mourishitz**
Making changes for the https://github.com/jannikmi/timezonefinder/issues/195 issue

### CODE REVIEW

**Comment by Mourishitz** [comment]
Done! I had to force push in order to reset HEAD~ of a wrong commit I made on my local repository, let me know if any update is required, I look forward on contributing to the project as soon as possible!

**Comment by jannikmi** [comment]
Strange, but it did not work. the warning is still showing. could you please look into how other repositories have fixed this (look at latest github action workflows)

**Comment by Mourishitz** [comment]
Sure, I'll do it and come back with an answer (and a commit if necessary)

**Comment by Mourishitz** [comment]
It seems that the actions packages are not all available in version 3 already, I looked trough the latest versions and fixed with the best available version for each one.

I used as my main reference this documentation: https://docs.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions#using-a-specific-nodejs-version
Also, I checked actions versions using these:
- actions/checkout: https://github.com/actions/checkout
- pre-commit/action: https://github.com/pre-commit/action
- actions/setup-python: https://github.com/actions/setup-python

**Comment by Mourishitz** [comment]
Oh, I just saw that, I'll try to run it locally on my fork to find the best ones and find more documentations about the versions

**Comment by Mourishitz** [comment]
I have just refactored some changes, unfortunately I couldn't test it on my local repository due to repository secrets, hope this one do the work for us!

**Comment by jannikmi** [comment]
Thanks. Seems like it worked!

there is a new error:

`Unexpected input(s) 'node-version', `

could you please remove the „with“ parts?

**Comment by jannikmi** [comment]
@Mourishitz please have a look again.

**Comment by Mourishitz** [comment]
Sure, just noticed the problem here..

We now have two options, the test has passed even when GitHub actions said it was unexpected, so I don't think it is necessary anymore and we can remove this. Or, if really necessary we can try to pass it like

`--token=${{ secrets.GITHUB_TOKEN }}`

but, as I don't have enough knowledge about the impacts of this chance, I would like to discuss before commiting this changes. I do think removing is a better option because I also can't test it locally, so I don't know what to expect when running --token inside the 'extra_args' block

**Comment by jannikmi** [comment]
@Mourishitz Thanks for your contribution!

**Pull request merged**
